### ISSUE TITLE
Applet crashes if nfs-mount-browser disappers

### ISSUE THREAD

**Issue by bmario** [bmario/nfs-mount#1]
The applet crashes if the DBus interface from the Nfs-mount-browser disappears, because
the daemon gets restarted or has crashed.

Output is like:
Traceback (most recent call last):
  File "/usr/local/bin/nfs-mount-systray.py", line 116, in show_menu
    si = self.nfsmount.getShareInfo(share)
  File "/var/lib/python-support/python2.5/dbus/proxies.py", line 140, in **call**
    **keywords)
  File "/var/lib/python-support/python2.5/dbus/connection.py", line 607, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.34 was not provided by any .service files

**Comment by bmario** [comment]
Fixed with commit http://github.com/bmario/nfs-mount/commit/8ff8e46850ab0e3d84dcd8bf727030e86762e5f6
